### ISSUE TITLE
[aws/kops-aws-platform] chart-repo.tf does not consider if cluster_name is not default

### ISSUE THREAD

**Issue by tegamckinney** [cloudposse/terraform-aws-components#190]
chart-repo.tf sets `cluster_name    = "${var.region}.${var.zone_name}"` however when deploying kops module there is the ability to set `cluster_name_prefix` which overrides the default `region` name.

Other modules in the root-module set `cluster_name` the same way.  Does it make sense to move the `cluster_name_prefix` logic to `aws/kops-aws-platform` or use some other ENV?

**Comment by osterman** [comment]
This is now out of date with the new reference architecture #286
