### ISSUE TITLE
Unsupported argument in module "iam_roles" in "iam-primary-roles" component

### ISSUE THREAD

**Issue by mathieusr** [cloudposse/terraform-aws-components#298]
Hi everyone,

I noticed a mistake in `iam-primary-roles` module causing error when plan this module with terraform

In iam-primary-roles when calling module `iam-roles` variable `assume_role` should be replaced by `tfstate_assume_role` like in `iam-delegated-modules`
https://github.com/cloudposse/terraform-aws-components/blob/e5360bb97a6d6baf640847b7301b47ce471ed068/modules/iam-primary-roles/providers.tf#L14-L19

https://github.com/cloudposse/terraform-aws-components/blob/e5360bb97a6d6baf640847b7301b47ce471ed068/modules/iam-delegated-roles/providers.tf#L14-L19

Mathieu

**Comment by Nuru** [comment]
Yes, sorry, we are changing the way we handle remote state in all the components. See #324

**Comment by mathieusr** [comment]
Thanks for your answer in all the modules the tfstate.tf and tfstate-context.tf will be deleted and replace with a remote-state.tf file ?

If yes do you need support to apply this change on each module ?

Thanks
