### ISSUE TITLE
A required `region` input parameter is missing in `variables.tf` of the module `modules/account-map/iam-roles`

### ISSUE THREAD

**Issue by iliazlobin** [cloudposse/terraform-aws-components#323]
## Description

The variable `region` referenced in a `terraform_remote_state` data source definition of the module `modules/account-map/iam-roles` is missing in `variables.tf`

The `modules/account-map/iam-roles` module is generally used in many upper level modules:
![image](https://user-images.githubusercontent.com/3456942/118975484-1b9d1380-b985-11eb-912b-185a315b2627.png)

It's used for the reason of deriving the assumption role (or profile) to configure AWS provider.

## Expected Behavior

Terraform doesn't trigger an error when launching a plan command and the AWS provider is given the right role to assume depending on how `account-map` is laid out.

## Steps to Reproduce
Set up an atmos stack with one of the modules that makes use of `iam-roles` and run `terraform plan` or an atmos wrapper command `atmos terraform plan iam-primary-roles -s gbl-identity`

**Comment by Nuru** [comment]
Our apologies, but these components are not quite ready for production use. We currently have 20+ PRs opened to fix all the problems. In this particular case, the published version of `iam-roles` uses the obsolete `tfstate.tf` pattern for retrieving remote state (see #324). Please wait for the updated version that will use `remote-state.tf`.

**Comment by Nuru** [comment]
This was fixed by #438 if not earlier
