### ISSUE TITLE
The link in the README.md for the vpc component is broken

### ISSUE THREAD

**Issue by it-praktyk** [cloudposse/terraform-aws-components#564]
## Describe the Bug

The link in [the line](https://github.com/cloudposse/terraform-aws-components/blob/master/modules/vpc/README.md?plain=1#L3) is broken. The 404 error page is returned instead.

**Comment by Nuru** [comment]
The referenced link is to a file that is to be provided by the user, detailing how they are assigning CIDRs to VPCs. It is not meant to be resolved in generic documentation.
