### ISSUE TITLE
aws-team-roles fails to plan  due to missing module

### ISSUE THREAD

**Issue by cpieper78** [cloudposse/terraform-aws-components#606]
https://github.com/cloudposse/terraform-aws-components/blob/decab2cc440a26fdc8b1829d549d129ebb23c4b3/modules/aws-team-roles/policy-eks-viewer.tf#LL4C24-L4C67

<img width="1049" alt="CleanShot 2023-03-24 at 15 45 12@2x" src="https://user-images.githubusercontent.com/98427213/227624713-efce10ee-52bb-4494-9f43-372cdfcef8a7.png">

**Comment by Nuru** [comment]
Fixed by #642
