### ISSUE TITLE
`ecs-service` component can't be applied because it depends on a module which doesn't support count

### ISSUE THREAD

**Issue by kevcube** [cloudposse/terraform-aws-components#635]
## Describe the Bug
Using the `ecs-service` component fails because it depends on the `datadog-configuration/datadog_keys` module which declares its own providers, therefore can't be used with `count`.

## Expected Behavior
`ecs-service` module works as shipped

## Steps to Reproduce
just `terraform validate` on ecs-service.

## Screenshots
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/716806/231574165-b7c731d2-a745-4094-a53f-af77f5b1d4a9.png">

## Additional Context
Maybe the module reference needs a pinned version, this probably worked at one time, but doesn't now.

**Comment by Benbentwo** [comment]
> Maybe the module reference needs a pinned version, this probably worked at one time, but doesn't now.

😄 It's always good to pin. We try to reduce breaking changes but sometimes for the sake of development speed or the lifecycle of a component we have to introduce them.

That being said, I THINK if you roll forward this should be solved, as mentioned in the above PR.

If this isn't the case can you reopen and ping me?
