### ISSUE TITLE
Various references broken (mainly to reference architecture)

### ISSUE THREAD

**Issue by hans-d** [cloudposse/terraform-aws-components#747]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help.

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
Various broken links:
(https://github.com/cloudposse/terraform-aws-components/blob/a63341e8fb54178294c4f42be78a9b2e0c205870/modules/account-map/README.md?plain=1#L7)

## Expected Behavior
Valid links

**Comment by osterman** [comment]
Please note this documentation Docusarus markdown and is the static documentation rendered to docs.cloudposse.com.

All links are validated via CI and working.

We are unable to manage duplicate copies of documentation on GitHub markdown as well as Docusarus markdown, as it would lead to confusion as to which copy to edit, resulting in PRs to generated content.

**Comment by osterman** [comment]
Here is the corresponding link to the referenced example. https://docs.cloudposse.com/components/library/aws/account-map/

Also, it's worth mentioning that we use relative links so that they work in ephemeral preview environments of PRs.

**Comment by osterman** [comment]
Apologies, but it does appear that our public links are not validated. I see the broken links as well. Will get fixed asap.

**Comment by milldr** [comment]
resolved by #749
