### ISSUE TITLE
aws-backups: variables unused / deprecated

### ISSUE THREAD

**Issue by hans-d** [cloudposse/terraform-aws-components#977]
### Describe the Bug

With the upgrade to aws-backup v1 various variables became obsolote, buta re not marked as such

### Expected Behavior

variables functioning,and/or marked deprecated, or fully removed

### Steps to Reproduce

see code

### Additional Context

https://github.com/cloudposse/terraform-aws-components/blob/633f81082fb13cdf5febebdf5aee77505d585e04/modules/aws-backup/variables.tf#L18

**Comment by hans-d** [comment]
Example in the readme must also be updated

**Comment by oycyc** [comment]
Saw this issue after trying to use this component, made a PR for this: https://github.com/cloudposse/terraform-aws-components/pull/992

**Comment by oycyc** [comment]
https://github.com/cloudposse/terraform-aws-components/pull/992 is merged

**Comment by hans-d** [comment]
thanks @oycyc
