### ISSUE TITLE
`eks/karpenter` and `eks/karpenter-provisioner` does not support latest Karpenter

### ISSUE THREAD

**Issue by sgtoj** [cloudposse/terraform-aws-components#982]
### Describe the Bug

The current `eks/karpenter` and `eks/karpenter-provisioner` component doesn't support the latest Karpenter v0.34.0. This is due to multiple changes, and eventual breaking changes, that Karpenter introduced between v0.31.0 and v0.34.0. 

### Expected Behavior

Work with the latest Karpenter. 

### Steps to Reproduce

Deploy `eks/karpenter` w/ `chart_version` set to `0.34.0`. 

### Screenshots

N/A

### Environment

- Not realevant. 

### Additional Context

I am working on a PR that will address the issues. However, to keep the components simple, it will only support Karpenter v0.34.0 or newer.

**Comment by Nuru** [comment]
Fixed by:

- #1039 
- #1056
